# Site Settings
title: Site
email: py.nishant@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://taniarascia.github.io"
twitter_username: wazusin
github_username:  nishuranjan
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM